sudo: true
language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip3 install -r requirements.txt
script:
  - py.test --cov=./test
after_script:
  - pytest test/
after_success:
  - codecov --token=4ecf15c6-3a4c-43f2-82ba-1b0df712079c
